services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./storage/dynamic_config:/usr/local/etc/haproxy/dynamic_config:rw
      - ./storage/certs:/usr/local/etc/haproxy/certs:rw
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-f", "/usr/local/etc/haproxy/dynamic_config/", "-W"] 
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
